name: Test_Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      - name: Make Directory for results
        run: mkdir -p testResult
          
      - name: Run POSTMAN collection
        run: |
          newman run APITests.postman_collection.json -e MeuAmbiente.postman_environment -r htmlextra --reporter-htmlextra-export testResult/htmlreport.html --reporter-htmlextra-darkTheme > testResult/runreport1.html
          
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResult
